# torch basic

## linear regression

In [50]:
import torch

def linear(x, W, b):
    y = torch.mm(x, W) + b # mm: [n, m] x [m,p] = [n,p]
    return y

x = torch.randint(0,10,size=(3,2))
W = torch.randint(0,10,size=(2,4))
b = torch.randint(0,10,size=(4,))

y = linear(x, W, b) # [3, 2] X [2, 4] = [3, 4] + [4] = [3, 4] + [3, 4] = [3, 4]

print(x.shape)
print(W.shape)
print(b.shape)
print(y.shape)

torch.Size([3, 2])
torch.Size([2, 4])
torch.Size([4])
torch.Size([3, 4])


In [51]:
print(torch.mm(x, W))
print(b)
print(y)

tensor([[18,  0,  0,  6],
        [24, 16, 14, 20],
        [15,  8,  7, 11]])
tensor([9, 6, 9, 5])
tensor([[27,  6,  9, 11],
        [33, 22, 23, 25],
        [24, 14, 16, 16]])


## basic linear 

In [52]:
import torch
import torch.nn as nn

class MyLinear(nn.Module):
    def __init__(self, input_size, output_size):
        super().__init__()
        self.W = torch.FloatTensor(input_size, output_size)
        self.b = torch.FloatTensor(output_size)
    
    def forward(self, x):
        y = torch.mm(x, self.W) + self.b
        
        return y
    
x = torch.FloatTensor(16, 10)
linear = MyLinear(10, 5)
y = linear(x)

params =[p.size() for p in linear.parameters()]
print(params)

[]


In [53]:
import torch
import torch.nn as nn

class MyLinear(nn.Module):
    def __init__(self, input_size, output_size):
        super().__init__()
        self.W = nn.Parameter(torch.FloatTensor(input_size, output_size), requires_grad=True)
        self.b = nn.Parameter(torch.FloatTensor(output_size), requires_grad=True)
    
    def forward(self, x):
        y = torch.mm(x, self.W) + self.b
        
        return y
    
x = torch.FloatTensor(16, 10)
linear = MyLinear(10, 5)
y = linear(x)

params =[p.size() for p in linear.parameters()]
print(params) # w, b를 추적. y로부터 미분한 기울기를 구할 수 있다

[torch.Size([10, 5]), torch.Size([5])]


In [54]:
import torch
import torch.nn as nn

class MyLinear(nn.Module):
    def __init__(self, input_size, output_size):
        super(MyLinear, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
    
    def forward(self, x):
        y = self.linear(x)
        
        return y
    
x = torch.FloatTensor(16, 10)
linear = MyLinear(10, 5)
y = linear(x)

params =[p.size() for p in linear.parameters()]
print(params)
print(linear)

[torch.Size([5, 10]), torch.Size([5])]
MyLinear(
  (linear): Linear(in_features=10, out_features=5, bias=True)
)


In [55]:
x = torch.FloatTensor(16, 10)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         3.7801e-14, 4.5723e-41, 3.7801e-14, 4.5723e-41],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000

In [56]:
objective = 100

linear = MyLinear(10, 5)
y = linear(x)
print(y)
print(y.shape)

tensor([[ 0.0052,  0.0692, -0.1890, -0.0361,  0.1834],
        [ 0.0052,  0.0692, -0.1890, -0.0361,  0.1834],
        [ 0.0052,  0.0692, -0.1890, -0.0361,  0.1834],
        [ 0.0052,  0.0692, -0.1890, -0.0361,  0.1834],
        [ 0.0052,  0.0692, -0.1890, -0.0361,  0.1834],
        [ 0.0052,  0.0692, -0.1890, -0.0361,  0.1834],
        [ 0.0052,  0.0692, -0.1890, -0.0361,  0.1834],
        [ 0.0052,  0.0692, -0.1890, -0.0361,  0.1834],
        [ 0.0052,  0.0692, -0.1890, -0.0361,  0.1834],
        [ 0.0052,  0.0692, -0.1890, -0.0361,  0.1834],
        [ 0.0052,  0.0692, -0.1890, -0.0361,  0.1834],
        [ 0.0052,  0.0692, -0.1890, -0.0361,  0.1834],
        [ 0.0052,  0.0692, -0.1890, -0.0361,  0.1834],
        [ 0.0052,  0.0692, -0.1890, -0.0361,  0.1834],
        [ 0.0052,  0.0692, -0.1890, -0.0361,  0.1834],
        [ 0.0052,  0.0692, -0.1890, -0.0361,  0.1834]],
       grad_fn=<AddmmBackward0>)
torch.Size([16, 5])


In [57]:
loss = abs(objective - y.sum()) # Absolute Error
print(loss)

loss.backward() # gt에서 y를 뺀 것이므로 역시 추적 대상, 여기서의 미분값을 계산

tensor(99.4783, grad_fn=<AbsBackward0>)


In [58]:
# Training...
linear.eval()
# Do some inference process.
linear.train()
# Restart training, again.

MyLinear(
  (linear): Linear(in_features=10, out_features=5, bias=True)
)

In [59]:
import random

import torch
import torch.nn as nn

class MyModel(nn.Module):

    def __init__(self, input_size, output_size):
        super(MyModel, self).__init__()

        self.linear = nn.Linear(input_size, output_size)

    def forward(self, x):
        y = self.linear(x)

        return y

In [60]:
def ground_truth(x):
    return 3 * x[:, 0] + x[:, 1] - 2 * x[:, 2]

In [61]:
def train(model, x, y, optim):
    # initialize gradients in all parameters in module.
    optim.zero_grad()# backward()는 계속 값을 누적하므로 매번 gradient를 0으로 만들어야 한다.

    # feed-forward
    y_hat = model(x)
    # get error between answer and inferenced.
    loss = ((y - y_hat)**2).sum() / x.size(0) # 직접 계산할 수도 있고 pytorch에서 제공하는 loss function을 사용할 수도 있다.

    # back-propagation
    loss.backward()

    # one-step of gradient descent
    optim.step()

    return loss.data

In [62]:
batch_size = 1
n_epochs = 1000
n_iter = 10000

model = MyModel(3, 1)
optim = torch.optim.SGD(model.parameters(), lr=0.0001, momentum=0.1)

print(model)

MyModel(
  (linear): Linear(in_features=3, out_features=1, bias=True)
)


In [63]:
for epoch in range(n_epochs):
    avg_loss = 0

    model.train()
    for i in range(n_iter):
        x = torch.rand(batch_size, 3)
        y = ground_truth(x.data)

        loss = train(model, x, y, optim)

        avg_loss += loss
    avg_loss = avg_loss / n_iter

    # simple test sample to check the network.
    x_valid = torch.FloatTensor([[.3, .2, .1]])
    y_valid = ground_truth(x_valid.data)

    model.eval()
    y_hat = model(x_valid)

    print(avg_loss, y_valid.data[0], y_hat.data[0, 0])

    if avg_loss < .1: # finish the training if the loss is smaller than .1.
        break

tensor(1.1259) tensor(0.9000) tensor(0.7942)
tensor(0.6151) tensor(0.9000) tensor(0.8466)
tensor(0.4261) tensor(0.9000) tensor(0.8808)
tensor(0.3014) tensor(0.9000) tensor(0.9007)
tensor(0.2083) tensor(0.9000) tensor(0.9312)
tensor(0.1479) tensor(0.9000) tensor(0.9322)
tensor(0.1019) tensor(0.9000) tensor(0.9416)
tensor(0.0733) tensor(0.9000) tensor(0.9459)


In [ ]:
# Note that tensor is declared in torch.cuda.
#x = torch.cuda.FloatTensor(16, 10)
#linear = MyLinear(10, 5)
# .cuda() let module move to GPU memory.
#linear.cuda()
#y = linear(x)

## torch application basic

In [64]:
# import 패키지

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.utils.data as data_utils

In [65]:
class MyModel(nn.Module):
    def __init__(self, X_dim, y_dim):
        super(MyModel, self).__init__()
        layer1 = nn.Linear(X_dim, 128)
        activation1 = nn.ReLU()
        layer2 = nn.Linear(128, y_dim)
        self.module = nn.Sequential(
            layer1,
            activation1,
            layer2
        )
        
    def forward(self, x):
        out = self.module(x)
        result = F.softmax(out, dim=1)
        return result        

In [ ]:
## pytorch 어플리케이션의 기본 구조

#for input, target in dataset:
#    optimizer.zero_grad()
#    output = model(input)
#    loss = loss_fn(output, target)
#    loss.backward()
#    optimizer.step()