# loss functions

## nn.L1Loss

In [1]:
# abs(x-y), MAE

import torch
import torch.nn as nn

loss = nn.L1Loss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)
output = loss(input, target)
output.backward()

print(input)
print(target)
print(output.item())

tensor([[ 0.9515,  1.4815, -0.9133,  0.9616,  0.7851],
        [ 0.0433, -1.1205, -0.8181, -0.3065, -0.3884],
        [-0.6500, -0.5670,  1.7960,  1.0996, -0.8126]], requires_grad=True)
tensor([[ 0.7638,  0.1697,  0.5179,  0.2931, -1.4886],
        [ 0.8677,  1.0024,  0.1792, -1.4559, -1.1579],
        [-0.2806,  0.3791,  0.7442, -1.4809,  0.3112]])
1.1871854066848755


## nn.MSELoss

In [2]:
# (x-y)^2

import torch
import torch.nn as nn

loss = nn.MSELoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)
output = loss(input, target)
output.backward()

print(input)
print(target)
print(output.item())

tensor([[-0.7874, -0.0509,  0.4278,  0.9672,  0.9781],
        [-0.0856, -0.5680, -0.4007, -0.1596, -1.2672],
        [-0.3140, -0.8652, -1.0791,  0.5242, -1.8832]], requires_grad=True)
tensor([[ 0.4929, -0.2517,  2.1699, -0.3382,  1.0109],
        [ 1.7034, -1.1957,  0.5380, -1.3834, -2.1108],
        [-0.5133, -1.2245, -0.3923, -0.8770,  0.3416]])
1.3772587776184082


## nn.CrossEntropyLoss

In [3]:
# C개 아이템을 classify할 때 사용
# input은 (N, C), target은 (N), output은 scalar (N)
# 즉 input중 가장 높은 확률인 아이템이 몇번째인가?가 target이고 그에 따른 loss를 계산한다.

import torch
import torch.nn as nn

loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(input, target)
output.backward()

print(input)
print(target)
print(output.item())

tensor([[ 0.1627,  0.2585, -0.7961,  1.7504, -0.3878],
        [ 0.1575,  0.4941,  1.8837, -0.1701,  0.4336],
        [-0.2190, -0.3837, -0.4038,  1.8046, -2.4064]], requires_grad=True)
tensor([3, 0, 1])
1.7655202150344849


## nn.CTCLoss

In [ ]:
import torch
import torch.nn as nn

# Target are to be padded
T = 50      # Input sequence length
C = 20      # Number of classes (including blank)
N = 16      # Batch size
S = 30      # Target sequence length of longest target in batch (padding length)
S_min = 10  # Minimum target length, for demonstration purposes

# Initialize random batch of input vectors, for *size = (T,N,C)
input = torch.randn(T, N, C).log_softmax(2).detach().requires_grad_()

# Initialize random batch of targets (0 = blank, 1:C = classes)
target = torch.randint(low=1, high=C, size=(N, S), dtype=torch.long)

input_lengths = torch.full(size=(N,), fill_value=T, dtype=torch.long)
target_lengths = torch.randint(low=S_min, high=S, size=(N,), dtype=torch.long)
ctc_loss = nn.CTCLoss()
loss = ctc_loss(input, target, input_lengths, target_lengths)
loss.backward()
print(input)
print(target)
print(loss.item())

 # Target are to be un-padded
T = 50      # Input sequence length
C = 20      # Number of classes (including blank)
N = 16      # Batch size

# Initialize random batch of input vectors, for *size = (T,N,C)
input = torch.randn(T, N, C).log_softmax(2).detach().requires_grad_()
input_lengths = torch.full(size=(N,), fill_value=T, dtype=torch.long)

# Initialize random batch of targets (0 = blank, 1:C = classes)
target_lengths = torch.randint(low=1, high=T, size=(N,), dtype=torch.long)
target = torch.randint(low=1, high=C, size=(sum(target_lengths),), dtype=torch.long)
ctc_loss = nn.CTCLoss()
loss = ctc_loss(input, target, input_lengths, target_lengths)
loss.backward()
print(input)
print(target)
print(loss.item())

## nn.NLLLoss

In [ ]:
import torch
import torch.nn as nn

m = nn.LogSoftmax(dim=1)
loss = nn.NLLLoss()
# input is of size N x C = 3 x 5
input = torch.randn(3, 5, requires_grad=True)
# each element in target has to have 0 <= value < C
target = torch.tensor([1, 0, 4])
output = loss(m(input), target)
output.backward()

# 2D loss example (used, for example, with image inputs)
N, C = 5, 4
loss = nn.NLLLoss()
# input is of size N x C x height x width
data = torch.randn(N, 16, 10, 10)
conv = nn.Conv2d(16, C, (3, 3))
m = nn.LogSoftmax(dim=1)
# each element in target has to have 0 <= value < C
target = torch.empty(N, 8, 8, dtype=torch.long).random_(0, C)
output = loss(m(conv(data)), target)
output.backward()
print(input)
print(target)
print(output.item())

## nn.PoissonNLLLoss

In [ ]:
import torch
import torch.nn as nn

loss = nn.PoissonNLLLoss()
log_input = torch.randn(5, 2, requires_grad=True)
target = torch.randn(5, 2)
output = loss(log_input, target)
output.backward()
print(input)
print(target)
print(output.item())

## nn.KLDivLoss

## nn.BCELoss

In [ ]:
# 분류가 두가지인 경우 사용

import torch
import torch.nn as nn

m = nn.Sigmoid()
loss = nn.BCELoss()
input = torch.randn(3, requires_grad=True)
target = torch.empty(3).random_(2)
output = loss(m(input), target)
output.backward()
print(input)
print(target)
print(output.item())

## nn.BCEWithLogitsLoss

In [ ]:
import torch
import torch.nn as nn

loss = nn.BCEWithLogitsLoss()
input = torch.randn(3, requires_grad=True)
target = torch.empty(3).random_(2)
output = loss(input, target)
output.backward()
print(input)
print(target)
print(output.item())

## nn.MarginRankingLoss

## nn.HingeEmbeddingLoss

## nn.MultiLabelMarginLoss

In [ ]:
import torch
import torch.nn as nn

loss = nn.MultiLabelMarginLoss()
x = torch.FloatTensor([[0.1, 0.2, 0.4, 0.8]])
# for target y, only consider labels 3 and 0, not after label -1
y = torch.LongTensor([[3, 0, -1, 1]])
output = loss(x, y)
print(x)
print(y)
print(output.item())

## nn.SmoothL1Loss

## nn.SoftMarginLoss

## nn.MultiLabelSoftMarginLoss

## nn.CosineEmbeddingLoss

## nn.MultiMarginLoss

## nn.TripletMarginLoss

In [ ]:
import torch
import torch.nn as nn

triplet_loss = nn.TripletMarginLoss(margin=1.0, p=2)
anchor = torch.randn(100, 128, requires_grad=True)
positive = torch.randn(100, 128, requires_grad=True)
negative = torch.randn(100, 128, requires_grad=True)
output = triplet_loss(anchor, positive, negative)
output.backward()
print(input)
print(target)
print(output.item())