# torch basic

## tensor operations

In [35]:
import torch

# load_iris
x = torch.randn(150, 4, dtype=torch.float)
#w = torch.tensor([[1.0,2.0], [3.0,4.0], [5.0,6.0]])
w = torch.rand(4, 3, requires_grad=True)
print("x size:", x.size())
print("w size:", w.size())

x size: torch.Size([150, 4])
w size: torch.Size([4, 3])


In [36]:
b = torch.randn(150, 3, dtype=torch.float, requires_grad=True)
print("b:", b.size())

b: torch.Size([150, 3])


In [37]:
xw = torch.mm(x, w)
print("xw size:", xw.size())

xw size: torch.Size([150, 3])


In [38]:
result = xw + b
print("result size:", result.size()) 

result size: torch.Size([150, 3])


In [39]:
result

tensor([[ 6.3794e-01,  2.2132e+00, -4.8552e-01],
        [-2.2069e-01,  4.1083e-01, -6.8882e-01],
        [ 2.6448e-01,  1.7096e+00,  2.5173e+00],
        [-3.0175e+00, -1.4739e+00, -6.4085e-02],
        [ 1.2557e-01,  1.4500e+00, -1.9625e+00],
        [-1.5184e+00, -1.0893e+00, -6.6307e-01],
        [-6.7182e-02,  1.1941e+00,  1.0157e+00],
        [ 2.1091e+00,  3.1214e-01,  1.2891e-01],
        [ 1.8271e+00,  1.4863e+00,  9.5009e-02],
        [-1.2972e+00,  1.4136e+00,  4.2055e-01],
        [ 1.0494e+00,  1.8202e+00,  1.3474e+00],
        [ 5.4375e-01,  6.0335e-01, -7.9175e-01],
        [ 3.0530e+00, -5.5490e-02, -7.5288e-02],
        [ 1.2276e+00,  2.1196e+00,  9.1204e-01],
        [ 2.0656e-01, -1.9716e-01, -3.1050e-02],
        [-1.1832e+00,  2.5805e+00,  5.1938e-01],
        [-1.3013e+00, -8.4359e-01, -1.1017e-03],
        [ 1.9280e+00,  1.5656e+00,  8.8324e-01],
        [-1.7725e+00, -1.6184e+00, -1.9612e+00],
        [ 5.3552e-02,  1.1362e+00,  2.5349e-02],
        [-1.9843e+00

## broadcasting 

In [40]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1.shape, m2.shape)
print(m1 + m2)

torch.Size([1, 2]) torch.Size([1, 2])
tensor([[5., 5.]])


In [41]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1.shape, m2.shape)
print(m1 + m2)

torch.Size([1, 2]) torch.Size([1])
tensor([[4., 5.]])


In [42]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
print(m1.shape)
m2 = torch.FloatTensor([[3], [4]])
print(m2.shape)
print(m1 + m2)

torch.Size([1, 2])
torch.Size([2, 1])
tensor([[4., 5.],
        [5., 6.]])


## mean

In [43]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [44]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.mean())

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)


In [45]:
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


## max / argmax

In [46]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.shape)

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])


In [47]:
print(t.max()) # Returns one value: max
print(t.max(dim=0)) # Returns two values: max and argmax

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [48]:
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])
print('Argmax: ', t.argmax(dim=0))

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])
Argmax:  tensor([1, 1])


In [49]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
